#!/usr/bin/env python3
"""Turn a Maze into a Gazebo world: the .sdf, and the .json beside it.

    python3 -m maze_solver.maze_gen --seed 7 --cols 12 --rows 12 \
            --out ~/maze_solver_ws/mazes/maze_007.sdf

The pairing matters and it is the same contract the road projects used: the
.sdf is what Gazebo loads, the .json is what every ROS node loads, and both are
written in one call from one Maze object so they cannot describe different
mazes. Maze.from_meta rebuilds the graph exactly from the .json, so the planner
searches the same walls the lidar will hit.

WHY THE TERRAIN IS PAINTED AND NOT MODELLED

A mud patch is a visual tile 8 mm tall with no collision geometry. It is not
soft ground, and the physics engine knows nothing about it. The slow-down is
applied by path_driver.py, which looks up the cell it is in and divides its
speed by that cell's multiplier.

Simulating real soft ground would mean per-cell friction surfaces and a car
that bogs down - far more interesting physics, and completely wrong for this
project. The number the planner minimises has to be the number the stopwatch
measures, exactly, or the whole demonstration that 'UCS finds the faster route'
becomes a claim about a friction model rather than about search. So the cost
model is defined in one place and obeyed literally.

8 mm is also below both sensor thresholds - the lidar plane sits at 70 mm - so
no algorithm can accidentally see the terrain as an obstacle.
"""
import argparse
import json
import math
import os

from maze_solver.maze import DEFAULTS, TERRAIN, TERRAIN_COST, Maze

HEAD = '''<?xml version="1.0" ?>
<!-- generated by maze_solver.maze_gen : %(cols)dx%(rows)d cells, corridor %(corr).2f m,
     %(kind)s, %(slow)d slow cells -->
<sdf version="1.9">
  <world name="maze">
    <physics name="fast" type="ignored">
      <max_step_size>0.004</max_step_size>
      <real_time_factor>1.0</real_time_factor>
    </physics>
    <plugin filename="gz-sim-physics-system" name="gz::sim::systems::Physics"/>
    <plugin filename="gz-sim-user-commands-system" name="gz::sim::systems::UserCommands"/>
    <plugin filename="gz-sim-scene-broadcaster-system" name="gz::sim::systems::SceneBroadcaster"/>
    <plugin filename="gz-sim-sensors-system" name="gz::sim::systems::Sensors">
      <render_engine>ogre2</render_engine>
    </plugin>
    <plugin filename="gz-sim-imu-system" name="gz::sim::systems::Imu"/>
    <plugin filename="gz-sim-contact-system" name="gz::sim::systems::Contact"/>
    <gravity>0 0 -9.8</gravity>
    <scene><ambient>0.86 0.86 0.86 1</ambient><background>0.52 0.70 0.88 1</background>
      <shadows>false</shadows></scene>
    <light type="directional" name="sun"><cast_shadows>false</cast_shadows>
      <pose>0 0 9 0 0 0</pose><diffuse>0.95 0.95 0.92 1</diffuse>
      <specular>0.2 0.2 0.2 1</specular><direction>-0.4 0.3 -0.9</direction></light>
    <model name="ground_plane"><static>true</static><link name="link">
      <collision name="collision"><geometry><plane><normal>0 0 1</normal>
        <size>200 200</size></plane></geometry></collision>
      <visual name="visual"><geometry><plane><normal>0 0 1</normal>
        <size>200 200</size></plane></geometry>
        <material><ambient>0.17 0.18 0.20 1</ambient><diffuse>0.21 0.22 0.25 1</diffuse></material></visual>
    </link></model>
'''

MARKER = '''    <model name="%(name)s"><static>true</static>
      <pose>%(x).4f %(y).4f 0.012 0 0 0</pose><link name="link">
      <visual name="v"><geometry><cylinder><radius>%(r).3f</radius>
        <length>0.02</length></cylinder></geometry>
        <material><ambient>%(amb)s</ambient><diffuse>%(dif)s</diffuse></material></visual>
    </link></model>'''


def _wall_boxes(maze):
    """Every wall segment as a collision box and a matching visual.

    One box per lattice edge rather than merging collinear runs into long
    boxes. Merging would produce a smaller .sdf, and it was not done: the
    control panel can toggle any single wall, so the .sdf has to be
    regenerated per edit anyway, and a one-to-one correspondence between a
    wall in the graph and a box in the world is worth far more when something
    disagrees than the file size is.
    """
    amb, dif = '0.30 0.34 0.42 1', '0.42 0.48 0.58 1'
    h = maze.wall_height
    out = []
    for i, (x, y, yaw, length, thick) in enumerate(maze.wall_segments()):
        out.append(
            '      <collision name="cw%d"><pose>%.4f %.4f %.4f 0 0 %.5f</pose>'
            '<geometry><box><size>%.4f %.4f %.4f</size></box></geometry></collision>'
            % (i, x, y, h / 2.0, yaw, length, thick, h))
        out.append(
            '      <visual name="vw%d"><pose>%.4f %.4f %.4f 0 0 %.5f</pose>'
            '<geometry><box><size>%.4f %.4f %.4f</size></box></geometry>'
            '<material><ambient>%s</ambient><diffuse>%s</diffuse></material></visual>'
            % (i, x, y, h / 2.0, yaw, length, thick, h, amb, dif))
    return out


def _terrain_tiles(maze):
    """Flat coloured tiles under the slow cells. Visual only - see the docstring."""
    out = []
    n = 0
    lut = {c: (a, d) for _, c, a, d in TERRAIN}
    for r in range(maze.rows):
        for c in range(maze.cols):
            t = maze.terrain[r][c]
            if t <= 1.0:
                continue
            amb, dif = lut.get(t, lut[TERRAIN_COST[-1]])
            x, y = maze.cell_centre(c, r)
            out.append(
                '      <visual name="t%d"><pose>%.4f %.4f 0.004 0 0 0</pose>'
                '<geometry><box><size>%.3f %.3f 0.008</size></box></geometry>'
                '<material><ambient>%s</ambient><diffuse>%s</diffuse></material></visual>'
                % (n, x, y, maze.corridor, maze.corridor, amb, dif))
            n += 1
    return out


def to_sdf(maze):
    sx, sy = maze.cell_centre(*maze.start)
    gx, gy = maze.goal_pose()
    st = maze.stats()
    parts = [
        HEAD % {'cols': maze.cols, 'rows': maze.rows, 'corr': maze.corridor,
                'kind': 'perfect (one solution)' if st['perfect']
                        else 'braided (loops present)',
                'slow': st['slow_cells']},
        '    <model name="terrain"><static>true</static><link name="link">',
        '\n'.join(_terrain_tiles(maze)),
        '    </link></model>',
        '    <model name="maze_walls"><static>true</static><link name="link">',
        '\n'.join(_wall_boxes(maze)),
        '    </link></model>',
        MARKER % {'name': 'start_marker', 'x': sx, 'y': sy,
                  'r': maze.corridor * 0.30,
                  'amb': '0.20 0.45 0.95 0.6', 'dif': '0.28 0.58 1.00 0.6'},
        MARKER % {'name': 'goal_marker', 'x': gx, 'y': gy,
                  'r': maze.goal_radius(),
                  'amb': '0.10 0.85 0.30 0.7', 'dif': '0.15 0.95 0.35 0.7'},
        '  </world>\n</sdf>\n',
    ]
    return '\n'.join(parts)


def write_maze(out_path, maze=None, **kw):
    """Generate a maze and write the .sdf / .json pair. Returns the metadata."""
    m = maze if maze is not None else Maze(**kw)
    os.makedirs(os.path.dirname(os.path.abspath(out_path)) or '.', exist_ok=True)
    with open(out_path, 'w') as f:
        f.write(to_sdf(m))
    meta = m.to_meta()
    meta['stats'] = m.stats()
    with open(os.path.splitext(out_path)[0] + '.json', 'w') as f:
        json.dump(meta, f, indent=2)
    return meta


def main():
    ap = argparse.ArgumentParser(description=__doc__.split('\n')[0])
    ap.add_argument('--out', required=True)
    for k in ('cols', 'rows', 'seed'):
        ap.add_argument('--' + k, type=int, default=DEFAULTS[k])
    for k in ('braid', 'rough', 'corridor', 'wall_thickness', 'wall_height'):
        ap.add_argument('--' + k.replace('_', '-'), type=float, default=DEFAULTS[k])
    ap.add_argument('--generator', default=DEFAULTS['generator'],
                    choices=('backtracker', 'prim'))
    a = ap.parse_args()
    meta = write_maze(a.out, cols=a.cols, rows=a.rows, seed=a.seed,
                      generator=a.generator, braid=a.braid, rough=a.rough,
                      corridor=a.corridor, wall_thickness=a.wall_thickness,
                      wall_height=a.wall_height)
    st = meta['stats']
    print('%s  %dx%d cells, %.1f x %.1f m, %s, %d junctions, %d slow cells'
          % (a.out, meta['cols'], meta['rows'], st['span_m'][0], st['span_m'][1],
             'perfect' if st['perfect'] else 'braided',
             st['junctions'], st['slow_cells']))


if __name__ == '__main__':
    main()
